import Navbar from '@/Components/SharedCompo/Nav/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/SharedCompo/Footer/Footer'
import AuthProvider from '@/Providers/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DocEye',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar></Navbar>
          {children}
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  )
}
