import Navbar from '@/Components/Homepage/Nav/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Homepage/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DocEye',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
