import React from 'react';
import { FaXmark } from 'react-icons/fa6';

const TermsModal = () => {
    return (
        <dialog id="terms_modal" className="modal">
            <div className="modal-box !p-0 !max-w-5xl" >
                <div className="modal-action relative mt-0">
                    <form method="dialog" className='p-5 pt-14'>
                        {/* Cross icon */}
                        <button className="absolute top-2 left-2 text-red-500 text-3xl outline-none rounded p-3 cursor-pointer"> <FaXmark></FaXmark> </button>

                        <h2 className='my-subtitle'>Terms & Conditions</h2>
                        <div className="modal-body"><span><p className='font-semibold'>THE FOLLOWING TERMS AND CONDITIONS (“T&amp;C”) GOVERN THE DOCTOR{"'"}S ACCESS TO AND USE OF DocEye (THE <strong>“PLATFORM” </strong>OR<strong> “DocEye”</strong>) OWNED AND OPERATED BY DocEye LIMITED, INCLUDING ALL CONTENT, FUNCTIONALITY AND SERVICES OFFERED HEREIN. THESE TERMS AND CONDITIONS CREATE A CONTRACT BETWEEN THE DOCTOR AND DocEye LIMITED. DocEye MAY IMMEDIATELY TERMINATE THESE T&amp;C OR ANY SERVICES OR GENERALLY CEASE TO OFFER OR DENY ACCESS TO THE SERVICES OR ANY PORTION THEREOF, AT ANY TIME FOR ANY REASON.</p>
                            <p className='font-semibold'>PLEASE READ THESE T&amp;C CAREFULLY BEFORE THE START USING THIS PLATFORM. BY CLICKING “AGREE/ACCEPT” THE DOCTOR AGREES TO BE BOUND BY THESE T&amp;C AT ALL TIMES. NON-ACCEPTANCE OF THE T&amp;CS SHALL DISALLOW THE DOCTOR TO USE THE PLATFORM.</p>
                            <p className='font-semibold'><strong>THE SERVICES </strong></p>
                            <ol>
                                <li>The PLATFORM constitutes a technology platform that facilitate healthcare and health-related services by Registered Medical the Doctor (“<strong>the Doctor</strong>” or <strong>“Medical Service Provider”</strong>) to patients, with the assistance of healthcare workers/professional, if any, using information and communication technologies (“<strong>the Services</strong>”/ “the Telemedicine”). The users of DocEye mobile application can access the Services via the Platform, subject to T &amp; C provided herein and applicable laws of Bangladesh. It is hereby acknowledged by the Doctor that as a Medical Service Provider, s/he are solely responsible for the quality and accuracy of healthcare consultations and health-related services in the capacity of an independent contractor. The Doctor further acknowledges and undertakes that, in the absence of a separate Employment Contract executed between DocEye and the Doctor, the Doctor would not be deemed to be an employee of DocEye or any of its affiliates.</li>
                                <li>The Doctors shall pursue sound medical practice to provide the Services and shall follow norms and protocols relating to physician-patient relationship, evaluation, management and treatment, informed consent, continuity of care, referral for emergency services, medical records, privacy and security of the patient records and exchange of information, prescribing and reimbursement, health education, counselling etc. in accordance with the Bangladesh Medical and Dental Council Telemedicine Guidelines July 2020 (“<strong>the Guidelines</strong>”), the Bangladesh Medical and Dental Council Code of Professional Conduct, Etiquette and Ethics (“<strong>the Code of Conduct</strong>”), laws, rules, regulations and direction related to the Services published by the Ministry of Health and Family Welfare or other Directorates/offices from time to time. Additionally, the Doctors would abide by relevant provisions of the Information and Communication Technology Act, 2006, the Digital Security Act 2018, or any applicable rules enacted time to time for protecting patients{"'"} privacy and confidentiality and regarding the handling and transfer of such personal information of the patient.</li>
                                <li>Subject to the Doctor{"'"}s compliance with these T&amp;C, DocEye grants the Doctor a limited, non-exclusive, non-sublicensable, revocable, non-transferrable license to: (i) access and use the Platform on the Doctor{"'"}s device solely in connection with the Doctor{"'"}s use of the Services; and (ii) access and use any content, information and related materials that may be made available through the Services. Any rights not expressly granted herein are reserved by DocEye and DocEye{"'"}s licensors. The Doctor hereby covenants that it shall only provide the Services to legitimate registered users of DocEye, and in event, shall abuse or misuse the facility provided by DocEye.</li>
                            </ol>
                            <p className='font-semibold'><strong>REGISTRATION</strong></p>
                            <ol start="4">
                                <li>To create an account and access the Website/App, the Doctor represents that s/he is over the age of 18 and not barred from using the PLATFORM under applicable law.</li>
                                <li>By registering on DocEye as a Doctor/ Medical Service Providers, the Doctor represents and warrants that s/he is registered with Bangladesh Medical and Dental Council (“BMDC”) in accordance with the Bangladesh Medical and Dental Council Act, 2010, and are permitted to access and use the PLATFORM. It is further represented and warranted by the Doctor that no proceeding is pending against him/her before BMDC or any other regulator of medical services providers in Bangladesh, and/or that his/her BMDC registration is not suspended for any reason.</li>
                                <li>If the necessary information shared for verification is found to be untrue or misleading, the Doctor will be denied access to the PLATFORM. The Doctor agrees to indemnify, defend and hold DocEye harmless and compensate them for and against any and all claims, demands, causes of action, suits, actions, proceedings, damages, liabilities, losses, costs and expenses including attorney{"'"}s fees and expenses, whether direct or indirect, arising out of, incidental to, or resulting from his/her failure to provide accurate information during registration as a Doctor/Medical Service Provider in Bangladesh under the prevailing laws.</li>
                                <li>The Doctor represents and warrants that all information (full name, gender, birth date, BMDC Number, ID Info, active mobile number, email address, professional qualifications, experience, profile picture) and other relevant documents provided by the Doctor to register with DocEye are accurate, updated and shall always remain valid. Any change in the status of information will be immediately notified by the Doctor to DocEye.</li>
                                <li>The information collected from the Doctor will be held by DocEye and used in accordance with our Privacy Policy, which can be found at (“<a href="https://DocEye.com.bd/about/privacy-policy">Privacy Policy</a>”).</li>
                                <li>By registering with the PLATFORM, the Doctor agrees to abide by the T&amp;C at all times, to use the PLATFORM in accordance with the laws of Bangladesh, not abuse or misuse the PLATFORM in any way or breach privacy of patients, and not access or use the PLATFORM using any automated software.</li>
                                <li>Attempts to breach security of the PLATFORM on any computer or mobile network or access an account that does not belong to the Doctor on the PLATFORM is strictly prohibited.</li>
                                <li>To prevent fraud or abuse, only one registered account is allowed in the name of one Doctor. Any attempt to create additional accounts shall be invalid.</li>
                                <li>Doctor shall not attempt to create duplicate account(s) of patients to abuse or misuse the PLATFORM.</li>
                                <li>The Doctor will not use any copyright, trademark, or other proprietary rights of any third party nor remove the same while using the PLATFORM.</li>
                                <li>The PLATFORM shall, in no circumstances, be liable for any technical glitches beyond the PLATFORM{"'"}s control.</li>
                            </ol>
                            <p className='font-semibold'><strong>TERMS OF USE</strong></p>
                            <ol start="15">
                                <li>The service request for Telemedicine shall be initiated by the patient. Upon receipt of a request from the patient, the Doctor shall accept the request within 45 minutes of such request. Any failure to adhere to the timeline unjustifiably by the Doctor, may be deemed by DocEye to be a misconduct, and/or violation of T &amp; C.</li>
                                <li>The Doctor shall not suggest anyone to initiate such service or initiate such service by himself/herself using multiple devices or contact numbers as patient for fraudulent purposes which includes but is not limited to increasing number of consultations for any incentive packages available to Doctors, increase rating fraudulently by own multiple devices or inducing previously known users, provide positive reviews fraudulently by own multiple devices or inducing previously known users, etc.</li>
                                <li>The Doctors using the PLATFORM shall uphold the professional and medical ethical norms and standards as applicable in Bangladesh to traditional in-person care and adhere to core principle of the profession including protecting patient privacy and confidentiality.</li>
                                <li>If during a Telemedicine consultation, as per the judgment of the Doctor, the condition of a patient appears to be an emergency, the Doctor shall provide counselling, advise first-aid, and facilitate approval. In an emergency situation, an immediate in-person consultation should be strongly advised by the Doctor.</li>
                                <li>The Services must not be anonymous, the Doctor must verify and confirm the patient{"'"}s identity by name, age, address, email ID (if any), registered ID or any other identification as may be deemed to be appropriate. The Doctor must begin consultation by explicitly mentioning his/her name and credentials to the patient. In case of minor patients, the Service must be offered only if minor is attending the consultation along with an adult whose identity is ascertained by the Doctor.</li>
                                <li>The Doctor must obtain explicit consent from the patient to obtain the Telemedicine consultation, collect, and use personal information, medical data, and keep records of the case history, investigation reports, images, prescriptions, and electronic receipts, etc. as appropriate.</li>
                                <li>If the Doctor is of the opinion that physical examination is critical for consultation, s/he should not proceed with the consultation until a physical examination can be arranged through an in-person consultation.</li>
                                <li>Provided that an in-person examination is not necessary to manage the condition of the patient in the professional opinion of the Doctor, s/he shall provide health education, counselling and/or prescribe medicine, as is deemed appropriate by him/her in the context.</li>
                                <li>In the event of prescribing medications via the Platform, the Doctor should be satisfied that s/he has gathered adequate and relevant information about the patient{"'"}s medical condition and prescribed medicines are in the best interest of the patients. In prescribing medicines, the Doctor should strictly adhere to the directive prescribed by BMDC in the Guidelines or such other laws, directives, as may be relevant and applicable to such prescription.</li>
                                <li>The Doctor shall be professionally accountable in the same manner as traditional in-person consultation and must adhere to the restrictions provided in the Guidelines in respect of over-the-counter medications, prescribed medication for which diagnosis is possible by video consultation, add-on medications and prohibited medicines. The Doctor acknowledges that prescribing medicines without an appropriate diagnosis/provisional diagnosis will amount to a professional misconduct for which the Doctor will be liable in accordance with these T &amp; C.</li>
                                <li>The Doctor shall be solely responsible for providing Services, prescribing medicines, and consultation as per this T&amp;C and shall indemnify, defend and hold DocEye harmless and compensate them for and against any and all claims, demand, causes of action, suit, action, proceeding, damages, liabilities, losses, costs and expenses including attorney{"'"}s fees and expenses, whether direct or indirect, arising out of, incidental to, or resulting from compromise in quality of consultation, patient{"'"}s care or privacy and confidentiality, or violation of any prevailing laws.</li>
                                <li>The Doctor shall assist DocEye to respond to any query or issue by the patients within the 5 days of receiving query from DocEye and provide necessary solution.</li>
                                <li>The Doctor shall record and maintain digital trail/documentation of consultation on the Platform for such period as prescribed by DocEye from time to time including log or record of Telemedicine interaction (e.g. phone logs, email records, chat/test record, video integration logs etc), patient records, reports, documents, images, diagnostics, data etc (digital or otherwise) utilized in the Telemedicine consultation and prescription records, if any, in accordance with Clause _____ of this T &amp; C. The concerned patient will have the right to access his/her records maintained by the Doctors on the Platform in connection with the Telemedicine consultation session(s). The Doctor shall have the right to access the records of a patient only in connection with providing consultations to him/her on the Platform or in person. For the avoidance of doubt it is hereby stipulated that the Doctors shall not have the right to access the records of one patient(s) to provide consultation to a different patient.</li>
                            </ol>
                            <p className='font-semibold'>While collecting content and information directly from patients, the Doctor must provide notice about and obtain user consent to the collection and use of the content and information that are collected.</p>
                            <p className='font-semibold'>&nbsp;</p>
                            <p className='font-semibold'><strong>GENERAL POLICY</strong></p>
                            <ol start="28">
                                <li>The Doctor hereby agrees, understands, and consents to DocEye{"'"}s direct and indirect collection of information regarding the Doctor{"'"}s profiles, contact details, and practice, and make disclosure and publication of the same, to the extent the same is necessary for facilitating the provision of Services, and permitted by law. DocEye reserves the right to take down any Doctor{"'"}s profile as well as the right to display the profile of the Doctor, with or without notice to the concerned the Doctor. The information described in this Clause is collected for the purpose of facilitating interaction between the Doctors and patients. If any information displayed on the Website/App in connection with the Doctor and his/her profile is found to be incorrect, the concerned Doctor is required to inform DocEye immediately to enable DocEye to make the necessary amendments.</li>
                                <li>DocEye shall not be liable and responsible for the ranking of the Doctors on external websites and search engines.</li>
                                <li>DocEye shall not be responsible or liable in any manner to the Doctors for any losses, damages, injuries, or expenses incurred by the Doctors as a result of any disclosures or publications made by DocEye, where the Doctor has expressly or implicitly consented to the making of disclosures or publications by DocEye. If the Doctor had revoked such consent under the terms of the Privacy Policy, then DocEye shall not be responsible or liable in any manner to the Doctor for any losses, damage, injuries, or expenses incurred by the Doctor as a result of any disclosures made by DocEye prior to its actual receipt of such revocation of consent.</li>
                                <li>DocEye reserves the right to moderate the suggestions made by the Doctors through feedback and may remove any abusive or inappropriate or promotional content added on the Website/App. However, DocEye shall not be liable if any inactive, inaccurate, fraudulent, or non- existent profiles of the Doctors are added to the Website/App.</li>
                                <li>Telemedicine consultations should be treated the same way as in-person consultations from a fee perspective. Accordingly, The Doctors may charge an appropriate fee for the Telemedicine consultation provided that no premium will be charged by the Doctor solely for the reason of the consultation being a Telemedicine. DocEye shall deduct such amounts in such percentage, as is agreed between the Doctor and DocEye from time to time, as product &amp; service fee from the net fee receivable by the Doctor upon deduction of applicable tax and VAT.</li>
                                <li>The Doctor shall not provide and/or distribute any content through its Services which is immoral, obscene, scandalous, detrimental, prejudicial and/or injurious to the values, culture and/or sentiments of the people or any group of people or any community of Bangladesh and/or which may tarnish, damage, or negatively portray the image, goodwill, and reputation of any person, DocEye or its third-party partners. The Doctor is responsible for the content the Doctor shares on the PLATFORM and assume all risks related to it, including someone else{"'"}s reliance on its accuracy, or claim relating to intellectual property or other legal rights.&nbsp; The Doctor agrees that s/he will indemnify, defend and hold harmless DocEye for all claims resulting from the contents s/he posts.</li>
                                <li>The Doctor explicitly agrees that DocEye reserves the right to disclose the contents provided by the Doctors to a third party including content platforms.</li>
                                <li>The Doctor hereby represents, warrants, and acknowledges that s/he will use the Services in accordance with applicable law, and DocEye is an independent platform connecting the Doctors with the patients. Any contravention of any applicable law in the course of the Doctor{"'"}s use of these Services is his/her sole responsibility, and DocEye shall have no liability for the same.</li>
                                <li>The Doctor hereby agrees that s/he shall not:</li>

                                <li>insist on the patients to accept Consultations using the Services, when the patient is willing to travel to a facility and/or requests an in-person consultation except when such travel is not advisable in the prevailing situation, including in a pandemic situation;</li>
                                <li>misuse patient images and data, especially private and sensitive in nature;</li>
                                <li>prescribing medicines from the specific restricted list;</li>
                                <li>soliciting patients for Telemedicine through any advertisements or inducements</li>
                                <li>misuse this PLATFORM by conducting fraudulent consultation in order to reach any incentive provided by this PLATFORM.</li>
                                <li>When the patient is willing to accept Telemedicine consultation using the Services, the Doctor shall not insist on accepting in-person consultation and/or solicit patients from the PLATFORM for in-patient consultation.</li>
                                <li>The Doctors are solely responsible and liable for all, or any prescriptions issued including the accuracy of information provided through the PLATFORM following a Consultation.</li>
                                <li>The Doctor assents to the Cancellation and Refund Policy of the PLATFORM and shall assist DocEye to adhere to its obligation of Refund and Cancellation to the Patients or third-party partners.</li>
                                <li>The Doctor is solely responsible for determining the need for further face-to-face consultation and that in no circumstance shall the PLATFORM be liable for any misdiagnosis, acts or omissions of the Doctor.</li>
                                <li>The PLATFORM is not accountable, responsible or does not provide any protection for any interaction/s between the Doctor and the patients that take place beyond the PLATFORM.</li>
                                <li>The PLATFORM reserves the right and retains the sole discretion to keep or remove any the Doctor{"'"}s profile on the PLATFORM at any time; to incorporate or make available (as applicable) user reviews on the Doctor at any given time for the purposes of enhancing Service quality and equipping the Doctors with the information to allow the Doctor to make informed decision/s.</li>
                                <li>Rude, indecent, abusive, or improper or profane language, threatening, harassing, bullying, derogatory, discriminatory, defamatory, fraudulent comments, hate speech or remarks or messages communicated over the PLATFORM by the Doctor(s) to intimidate other users or any behaviour which may potentially damage the name or reputation of the PLATFORM shall result in suspension of the Doctor{"'"}s account.</li>
                                <li>Fraudulent consultation by the Doctor using this PLATFORM shall result in suspension of the Doctor{"'"}s account along with future legal action (both civil and criminal) brought by the PLATFORM as it deems fit.</li>
                                <li>The Doctor will refrain from taking any action which is intended to, could potentially or would reasonably be expected to harm the PLATFORM{"'"}s reputation or lead to unwanted or unfavourable publicity of the PLATFORM.</li>
                                <li>The PLATFORM retains the right, at its sole discretion to temporarily disable any Doctor{"'"}s account, for any reason, including security issues, reported improper behaviour, fraudulent consultation.</li>
                                <li>Any attempts to publish or send malicious content with the intent to compromise other user{"'"}s accounts or computer environments is strictly prohibited and may result in the suspension of the Doctor{"'"}s account.</li>
                                <li>Disclosure or posting other people{"'"}s private and confidential information or engaging in such activities may result in the suspension of the Doctor{"'"}s account.</li>
                            </ol>
                            <ol start="49">
                                <li>DocEye reserve the right to audit the consultations provided by the Doctor and the Doctor represents that it shall assist DocEye for the purpose of the said audit. If the audit disclosure any violation of the TCs and/or illegal, fraudulent activity of the Doctor, DocEye may pursue action against the Doctor including legal proceedings (civil or criminal) for fraud, breach of trust and cheating.</li>
                                <li>The PLATFORM reserves the right to make up to 2 monthly anonymous recorded consultations as a patient as part of improving the quality of the service provided by the Doctor. The Doctor will not receive any payment for those 2 quality control calls. The doctor will be notified about the quality control call after the call is conducted.</li>
                            </ol>
                            <p className='font-semibold'><strong>TRANSFER OF INFORMATION.</strong></p>
                            <ol start="51">
                                <li>The Doctor hereby agrees and acknowledges that in providing his/her services using the PLATFORM, all the information and records relating to the patients, including age, gender, symptoms, diagnosis and prescriptions, shall be recorded and stored on the Platform only. For the avoidance of doubt, it is hereby clarified, and acknowledged by the Doctor that s/he shall not record the aforementioned information relating to the patient on any other storage medium, whether electronically or manually. It is further agreed and understood by the Doctor that s/he shall not make a copy and/ or save the patient record on their own servers/ other medical facility infrastructure; nor would s/he extract the patient records/information from the Platform for use other than the patient consultation on the PLATFORM.</li>
                                <li>In the event that a patient registered on the platform (having been introduced to the Doctor through the Platform) chooses to visit the Doctor in-person, the concerned Doctor shall have access to the records of the patient maintained on the platform. The Doctor hereby agrees to record/update the information maintained on the Platform, including details such as symptoms, diagnosis, prescriptions etc., collected by the Doctor during such in person visit.</li>
                                <li>The Doctor hereby agrees that, except with the prior written consent from DocEye, &nbsp;s/he shall not share the information and records relating to the patients, including age, gender, symptoms, diagnosis and prescriptions (whether recorded by themselves, or made available to him/her by the Platform or the patient in the course of consultation on the Platform for the purpose of providing Telemedicine consultation), with any 3<sup>rd</sup> party, including another Doctor (whether or not such doctor is registered on the Platform). It is further agreed and understood by the Doctor that in the event that s/he chooses to deregister himself/herself from the Platform, his/her access to the patients records that s/he has consulted shall cease to be accessible to him/her.</li>
                                <li>The Doctor hereby consents, to the extent permitted by the law, to the sharing, disclosure or transfer of any information provided by the Doctor on the PLATFORM to any entities or related companies or subsidiaries of the PLATFORM in accordance with applicable laws.&nbsp;</li>
                            </ol>
                            <p className='font-semibold'><strong>PAYMENTS</strong></p>
                            <ol start="55">
                                <li>The Doctors will receive payments from DocEye weekly on every Monday for the consultation provided in the last 7 days upon deduction of any DocEye product &amp; service fee.</li>
                                <li>The Doctor agrees and consents to the deduction of payment processing fee, product &amp; service fee of such amounts in such percentage, as is agreed between the Doctor and DocEye from time to time, as from his/her net fees (after deduction of applicable tax and VAT) earned against consultation using the Services.</li>
                                <li>The Doctors will receive payment from the platform either by mobile banking (bKash, Nagad, Rocket) or to their bank account. If it's mobile banking, additional transaction fee may be applicable.</li>
                                <li>The PLATFORM reserves the right to increase payment processing fee, product &amp; service fee at any time. All the Doctors will be given 2 days{"'"} advance notice of any update on payment processing fee, product &amp; service fee of DocEye.</li>
                                <li>The Doctors warrant that s/he shall not charge any additional fees from the patients for the consultations provided using the PLATFORM.</li>
                                <li>DocEye may deduct such taxes, including VAT, relating to the payments applicable under the prevailing laws of Bangladesh.</li>
                                <li>The Doctor will not receive any payment for the quality control calls defined in section 50 of General Policy.</li>
                            </ol>
                            <p className='font-semibold'><strong>INDEMNITY</strong></p>
                            <ol start="62">
                                <li>The Doctor agrees to release, defend, indemnify, and hold the PLATFORM or any person associated with the PLATFORM including its respective affiliates, service providers, owners, partners, directors, officers, agents and employees (collectively as “<strong>Indemnified Parties</strong>”) free and harmless from and against any claims, liens, demands, causes of action and all losses to the extent arising from or in connection with any or all of: (a) any act, omission or negligence, non-performance and/or delay in the performance of obligations as a Doctor while providing consultations using the Services to the patients; (b) breach or violation of any of these T&amp;C; (c) anyintellectual property rights infringement including but not limited to copyrights, trademarks or any other rights, losses, damages, expenses, fines, fees or liability brought or instituted by a third party against the PLATFORM which is caused or contributed to, by the Doctor through the Doctor{"'"}s usage of the PLATFORM or the Doctor{"'"}s negligence or wilful misconduct; (d) any violation or alleged violation of any law; (e) violation of the rights of any third party, including patients and third party partners.</li>
                                <li>The PLATFORM or any person associated with the PLATFORM, is not liable for any personal injury, including death, attributable to or caused by the Doctor{"'"}s use or misuse of the PLATFORM, to the fullest extent permissible by law.</li>
                            </ol>
                            <p className='font-semibold'><strong>LIMITATION OF LIABILITY</strong></p>
                            <ol start="64">
                                <li>IN NO EVENT SHALL DocEye OR ITS AFFILIATES BE LIABLE FOR ANY INDIRECT OR CONSEQUENTIAL DAMAGES, PUNITIVE OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOST DATA, PERSONAL INJURY OR PROPERTY DAMAGE RELATED TO, IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE SERVICES INCLUDING LOSS OF PROFITS, INCURRED BY THE OTHER PARTY, ANY END-USER OF THE SERVICES OR ANY OTHER THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT OR OTHERWISE, IN CONNECTION WITH OR UNDER THIS TERMS AND CONDITIONS, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</li>
                                <li>DocEye SHALL NOT BE LIABLE FOR ANY DAMAGES, LIABILITY OR LOSSES ARISING OUT OF: (i)THE DOCTOR{"'"}S USE OF OR RELIANCE ON THE SERVICES OR THE DOCTOR{"'"}S INABILITY TO ACCESS OR USE THE SERVICES, OR (ii) ANY TRANSACTION OR RELATIONSHIP BETWEEN THE DOCTOR AND ANY THIRD PARTY. IN NO EVENT SHALL DocEye{"'"}S TOTAL LIABILITY TO THE DOCTOR IN CONNECTION WITH THE SERVICES FOR ALL DAMAGES, LOSSES AND CAUSE OF ACTION EXCEED ONE THOUSAND BANGLADESHI TAKA.</li>
                            </ol>
                            <p className='font-semibold'><strong>DISCLAIMER</strong></p>
                            <ol start="66">
                                <li>USE OF THE PLATFORM IS AT THE DOCTOR{"'"}S OWN RISK. THE WEBSTIRE/APP IS PROVIDED ON AN “AS IS” BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) DocEye DISCLAIMS ALL LIABILITY WHATSOEVER, WHETHER ARISING IN CONTRACT, TORT (INCLUDING) NEGLIGENE OR OTHERWISE IN RELATION TO THE WEBSITE/APP, AND (B) ALL IMPLIED WARRANTIES, TERMS AND CONDITIONS RELATING TO THE PLATFORM, INCLUDING WITHOUT LIMITATION ANY WARRANTY, TERM OR CONDITION AS TO ACCURACY, COMPLETENESS, SATISFACTIORY QUALITY, PERFORMANCE, FITNESS FOR PURPOSE OR ANY SPECIAL PURPOSE, AVAILABLITY, NON-INFRINGMENT, INFORMATION ACCURACY, INTEROPERABILITY, TITLE ARE, AS BETWEEN DocEye AND THE DOCTOR, HEREBY EXCLUDED, IN PARTICULAR, BUT WITHOUT PREJUCICE TO THE FOREGOING, DocEye ACCEPTS NO RESPONSIBILITY FOR ANY TECHNICAL FAILURE OF THE INTERNET, SECURITY BREACHES BY THIRD PARTY, AND/OR THE PLATFORM; OR ANY DAMAGE OR INJURY TO USERS OR THEIR EQUIPMENT AS A RESULT OF OR RELATING TO THEIR USE OF THE PLATFORM.</li>
                            </ol>
                            <p className='font-semibold'><strong>TERMINATION</strong></p>
                            <ol start="67">
                                <li>DocEye&nbsp;reserves the right to suspend or terminate a Doctor{"'"}s access to the PLATFORM with or without notice and to exercise any other remedy available under law where:
                                    <ol>
                                        <li>Such Doctor breaches any terms and conditions as provided herein;</li>
                                        <li>A third party reports violation of any of its right as a result of the Doctor offering the Services;</li>
                                        <li>DocEye is unable to verify or authenticate any information provide by the Doctor;</li>
                                        <li>DocEye has reasonable grounds for suspecting any illegal, fraudulent or abusive activity on part of such Doctor; or</li>
                                        <li>DocEye believes in its sole discretion that Doctor{"'"}s actions may cause legal liability for such Doctor, other or PLATFORM or are contrary to the interests of the DocEye.</li>
                                    </ol>
                                </li>
                            </ol>
                            <p className='font-semibold'>&nbsp;</p>
                            <ol start="68">
                                <li>Once temporarily suspended, indefinitely suspended or terminated, the Doctor may not continue to use the PLATFORM under the same account, a different account or re-register under a new account. On termination of an account due to the reasons mentioned herein, such Doctor shall no longer have access to data, messages, files and other material kept on the PLATFORM.</li>
                                <li>On suspension or termination of an account due to the reasons mentioned herein, DocEye shall retain the rights to withhold payments, fees, offers, benefits, or such other sum, unless the Doctor has provided documents and evidence supporting the contrary.</li>
                            </ol>
                            <p className='font-semibold'><strong>PROFILE OWNERSHIP AND EDITING RIGHTS</strong></p>
                            <ol start="70">
                                <li>DocEye ensures easy access to the Doctors by providing a tool to update his/her profile information. DocEye reserves the right of ownership of all the Doctor{"'"}s profile and photographs and to moderate the changes or updates requested by the Doctors. However, DocEye takes the independent decision whether to publish or reject the requests submitted for the respective changes or updates. The Doctor hereby represents and warrants that s/he is fully entitled under law to upload all contents uploaded by him/her as part of his/her profile or otherwise while using DocEye{"'"}s services, and that no such content breaches any third-party rights, including intellectual property rights. Upon becoming aware of a breach of the foregoing representation, DocEye may modify or delete parts of the Doctor{"'"}s profile information at its sole discretion with or without notice to the Doctor.</li>
                            </ol>
                            <p className='font-semibold'><strong>INTELLECTUAL PROPERTY RIGHTS</strong></p>
                            <ol start="71">
                                <li>PLATFORM and all its contents, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio and the design, selection and arrangement thereof are owned by DocEye, its licensors, and other providers of such material. The Doctor must not: a) modify copies of any materials from the PLATFORM; b) use any illustration, photographs, video or audio sequences or any graphics separately from the accompanying text; c) delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from the Platform; and d) reverse-engineer or otherwise attempt to steal the software/application code of the PLATFORM. Any use of the PLATFORM not expressly permitted by the T&amp;C is a breach of this T&amp;C and may violate copyright, trademark, and other laws.</li>
                            </ol>
                            <p className='font-semibold'><strong>REVIEWS AND FEEDBACK DISPLAY RIGHTS OF DocEye</strong></p>
                            <ol start="72">
                                <li>DocEye reserves the right to collect feedback about all the Doctors listed on the Website/App.</li>
                                <li>If DocEye determines that the Doctor has provided inaccurate information or enabled fraudulent feedback, DocEye reserves the right to immediately suspend the Doctor{"'"}s accounts with DocEye and make such declaration on the website alongside the Doctor{"'"}s name as determined by DocEye for the protection of its business and in the interests of users.</li>
                                <li>The Doctors understands that DocEye shall not be liable, under any event, for any comments or feedback given by any of the users in relation to the Services provided by the Doctors. The option of publishing or modifying or moderating or masking (where required by law or norm etc.) the feedback provided by users shall be solely at the discretion of DocEye.</li>
                                <li>DocEye reserves the right to report any violation of Code of Conduct, Ethical Standards on part of the Doctor to Executive Committee of Bangladesh Medical and Dental Council.</li>
                            </ol>
                            <p className='font-semibold'><strong>RELEVANCE ALGORITHM</strong></p>
                            <ol start="76">
                                <li>DocEye has designed the relevance algorithm in the best interest of the end-user and may adjust the relevance algorithm from time to time to improve the quality of the results given to the patients. It is a purely merit driven, proprietary algorithm which cannot be altered for specific doctors. DocEye shall not be liable for any effect on the Doctor{"'"}s business interests due to the change in the relevance algorithm.</li>
                            </ol>
                            <p className='font-semibold'><strong>INDEPENDENT SERVICES</strong></p>
                            <ol start="77">
                                <li>The Doctor{"'"}s use of each Service confers upon him/her only the rights and obligations relating to such Service, and not to any other service that may be provided by DocEye.</li>
                            </ol>
                            <p className='font-semibold'><strong>THE DOCTOR{"'"}S UNDERTAKING</strong></p>
                            <ol start="78">
                                <li>The Doctor is and shall be duly registered, licensed and qualified to practice medicine/ provide health care, wellness services, as per applicable laws/regulations/guidelines set out by competent authorities in Bangladesh. The Doctors shall not be part of any arrangement which will prohibit him/her from practicing medicine within the territory of Bangladesh. The Doctors shall at all times ensure that all the applicable laws that govern the Doctor shall be followed by him/her and utmost care shall be taken in terms of the consultation/ services being rendered. Furthermore, in providing Telemedicine consultation using DocEye, the Doctor shall strictly adhere to the mandates of the Guidelines.</li>
                            </ol>
                            <p className='font-semibold'><strong>USAGE IN PROMOTIONAL &amp; MARKETING MATERIALS</strong></p>
                            <ol start="79">
                                <li>In consideration of the various offerings and services provided by DocEye to the Doctors, the Doctors shall (to the extent permitted by the Doctor{"'"}s ethical standards, Code of Conduct and applicable law, and subject to his/her reasonable right to review and approve): (a) allow DocEye to include a brief description of the services provided to the Doctors in DocEye{"'"}s marketing, promotional and advertising materials; (b) allow DocEye to make reference to the Doctor in case studies, and related marketing materials; (c) serve as a reference to DocEye{"'"}s existing and potential clients; (d) provide video logs, testimonials, e-mailers, banners, interviews to the news media and provide quotes for press releases; (e) make presentations at conferences; and/or (f) use the Doctor{"'"}s name and/or logo, brand images, tag lines etc., within product literature, e-mails, press releases, social media and other advertising, marketing and promotional materials</li>
                            </ol>
                            <p className='font-semibold'><strong>MODIFICATION OF T&amp;C.</strong></p>
                            <ol start="80">
                                <li>The PLATFORM reserves the right, at its sole discretion, to change, modify or otherwise alter these Terms of Use at any time, by posting the updated T&amp;C on the PLATFORM.</li>
                                <li>It is the Doctor{"'"}s sole responsibility to check for any such changes, modification or alteration made to the T&amp;C and to familiarize himself/herself with it. Continued use of the PLATFORM shall be deemed as the Doctor{"'"}s consent to be bound by the T&amp;C. If the Doctor does not wish to be bound by the updated T&amp;C, the Doctor shall log out and discontinue the use of PLATFORM.</li>
                            </ol>
                            <p className='font-semibold'><strong>WAIVER</strong></p>
                            <ol start="82">
                                <li>No exercise or failure to exercise or delay in exercising any right or provision of the T&amp;C, shall not constitute a waiver of such right or provision by DocEye.</li>
                            </ol>
                            <p className='font-semibold'><strong>RELATIONSHIP</strong></p>
                            <ol start="83">
                                <li>DocEye and the Doctor are independent parties, and this T&amp;C does not establish any relationship of partnership, joint venture, employment, franchise or agency between the Doctor and DocEye.</li>
                            </ol>
                            <p className='font-semibold'><strong>SEVERABILITY</strong></p>
                            <ol start="84">
                                <li>If any part of this T&amp;C is construed to be illegal, invalid, frustrated, or unenforceable, for any reason, then, insofar as is practical and feasible, the remaining portions of the T&amp;C shall be deemed to be in full force and effect as if such invalid portions were not contained herein.</li>
                            </ol>
                            <p className='font-semibold'><strong>ASSIGNMENT</strong></p>
                            <ol start="85">
                                <li>The Doctor may not assign any part of its obligations under this T&amp;C to any third-party. Any attempt to assign, subcontract, or delegate is void in each instance. The Doctor gives his/her approval to DocEye for it to assign or transfer these T&amp;C in whole or in part to: (i) a subsidiary or affiliate; (ii) an acquirer of DocEye{"'"}s equity, business or assets; or (iii) a successor in a corporate restructuring.</li>
                            </ol>
                            <p className='font-semibold'><strong>TERMINATION</strong></p>
                            <ol start="86">
                                <li>The Doctor may end this legal agreement with DocEye at any time by deactivating his/her accounts and discontinuing the use of the PLATFORM.</li>
                                <li>DocEye may suspend or terminate the Doctor{"'"}s account or cease providing the Doctor with all or part of the Services at any time for reasons including but not limited to, if (i) the Doctor has violated these T &amp;C; (ii) the quality of services provided by the Doctor using the PLATFORM creates risk or possible legal exposure for DocEye; (iii) there is prolonged inactivity on the account; or (iv) DocEye{"'"}s provision of the Services to the Doctor is no longer commercially viable. Following suspension/termination of the Doctor{"'"}s account, DocEye will make reasonable efforts to notify the Doctor by the email address associated with the account or the next time the Doctor attempts to access his/her account, depending on the circumstances. Following termination, the relationship between the Doctor and DocEye shall cease, including without limitation the Doctor{"'"}s license to use the Services, except that the obligations to maintain patient{"'"}s privacy and confidentiality, to the extent that the obligation is mandated by law, shall continue to apply to the Doctor and DocEye.</li>
                            </ol>
                            <p className='font-semibold'><strong>DISPUTE RESOLUTION</strong></p>
                            <ol start="88">
                                <li>The PLATFORM encourages amicable settlement of any conflict/s that might arise among the Doctor, the PLATFORM or any other user including the patients. Any such conflict shall be resolved with the assistance or involvement of the PLATFORM. For addressing any grievances, or any other issues, transaction disputes the Doctor is encouraged to report the same to Customer Support here [INSERT LINK] (“Dispute Notice”). On service of the Dispute Notice, DocEye and the Doctor will attempt in good faith to resolve the dispute. If the dispute cannot be resolved by consultation within 28 (twenty-eight) days from the date of commencement of such dispute, then DocEye and the Doctor will jointly engage a mediator, for settlement of the dispute through mediation. The procedure for the mediation shall be in accordance with section 89A of the Code of Civil Procedure, 1908.</li>
                                <li>If either DocEye or the Doctor fail or refuse to agree to or participation in the mediation procedure or if in any event the dispute or difference is not resolved to satisfaction of both parties within 30 (thirty) days after it has been referred, the matter shall be referred for arbitration and settled in accordance with the Arbitration Act, 2001. The decision of the arbitrator of the arbitral tribunal will be final and binding upon the Parties. Each Party shall bear their costs of arbitration. The venue for arbitration shall be Dhaka and the proceedings of arbitration shall be held in the English language.</li>
                            </ol>
                            <p className='font-semibold'><strong>GOVERNING LAW AND JURISDICTION</strong></p>
                            <ol start="90">
                                <li>These T&amp;C shall be governed by and construed in accordance with the laws of Bangladesh. The courts of Bangladesh shall have exclusive jurisdiction in relation to all disputes or matters arising hereunder, and the parties irrevocably submit themselves to the exclusive jurisdiction of the courts in Bangladesh, for the resolution of any disputes arising under or in connection with this Agreement.</li>
                            </ol></span></div>
                    </form>
                </div>
            </div>
        </dialog>
    );
};

export default TermsModal;